import pycurl
from io import BytesIO
b_obj = BytesIO()
crl = pycurl.Curl()
usuario='admin'
contra='54321Av%'
#PASO 1 DEL API 
crl.setopt(crl.URL, 'http://10.1.1.20/cgi-bin/mediaFileFind.cgi?action=factory.create')
crl.setopt(crl.HTTPAUTH, crl.HTTPAUTH_DIGEST)
crl.setopt(crl.USERPWD, usuario + ':' + contra)
crl.setopt(crl.WRITEDATA, b_obj)
crl.perform()
crl.close()
pasouno= b_obj.getvalue()
datosobtenidos=pasouno.decode('utf8')
#SE GUARDA EL CODIGO CAPTURADO
ruta=open('codigodeteccion.txt','w')
ruta.write(datosobtenidos)
ruta.close()
#SE ABRE EL ARCHIVO Y SE GUARDAN LOS DATOS PARA APLICAR FILTRO
archivo = open("codigodeteccion.txt", "r")
guardar= archivo.read()
archivo.close()
#SE FILTRA SOLO EL CODIGO Y SE GUARDA EN UN NUEVO ARCHIVO
txt=open("codigoguardado.txt","w")
for i in range(7,len(guardar)):
    txt.write(guardar[i])
txt.close()
#SE ABRE EL ARCHIVO CON EL CODIGO Y SE GUARDA EN UNA VARIABLE PARA SU USO
txtdatos=open("codigoguardado.txt","r")
codigo=txtdatos.read()
codigo = codigo.replace("\r\n","")
codigo = codigo.replace("\r","")
codigo = codigo.replace("\n","")
txtdatos.close()
#PASO 2 DEL API
cualquiercosa = pycurl.Curl()
cualquiercosa.setopt(cualquiercosa.URL, 'http://10.1.1.20/cgi-bin/mediaFileFind.cgi?action=findFile&object='+codigo+'&condition.Channel=2&condition.Types[0]=dav&condition.Events[0]=FaceDetection&condition.StartTime=2020-07-16%2012:00:00&condition.EndTime=2020-08-01%2012:00:00&condition.VideoStream=Main')
cualquiercosa.setopt(cualquiercosa.HTTPAUTH, cualquiercosa.HTTPAUTH_DIGEST)
cualquiercosa.setopt(cualquiercosa.USERPWD, usuario + ':' + contra)
cualquiercosa.setopt(cualquiercosa.WRITEDATA, b_obj)
cualquiercosa.perform()
cualquiercosa.close()
pasodos = b_obj.getvalue()
#PASO 3 DEL API 
cualquier = pycurl.Curl()
cualquier.setopt(cualquier.URL, 'http://10.1.1.20/cgi-bin/mediaFileFind.cgi?action=findNextFile&object='+codigo+'&count=0')
cualquier.setopt(cualquier.HTTPAUTH, cualquiercosa.HTTPAUTH_DIGEST)
cualquier.setopt(cualquier.USERPWD, usuario + ':' + contra)
cualquier.setopt(cualquier.WRITEDATA, b_obj)
cualquier.perform()
cualquier.close()
pasotres= b_obj.getvalue()
#PASO 4 DEL API 
cualquier = pycurl.Curl()
cualquier.setopt(cualquier.URL, 'http://10.1.1.20/cgi-bin/mediaFileFind.cgi?action=findFile&object='+codigo+'&condition.Channel=2&condition.StartTime=2020-07-16%2012:00:00&condition.EndTime=2020-08-01%2012:00:00&condition.Types[0]=jpg&condition.Flags[0]=Event&condition.Events[0]=FaceDetection&condition.DB.FaceDetectionRecordFilter.ImageType=GlobalSence&condition.DB.FaceDetectionRecordFilter.Sex=Man&condition.DB.FaceDetectionRecordFilter.Age[0]=25&condition.DB.FaceDetectionRecordFilter.Age[1]=40&condition.DB.FaceDetectionRecordFilter.Glasses=1')
cualquier.setopt(cualquier.HTTPAUTH, cualquiercosa.HTTPAUTH_DIGEST)
cualquier.setopt(cualquier.USERPWD, usuario + ':' + contra)
cualquier.setopt(cualquier.WRITEDATA, b_obj)
cualquier.perform()
cualquier.close()
pasocuatro = b_obj.getvalue()
#PASO 5 DEL API
cualquier = pycurl.Curl()
cualquier.setopt(cualquier.URL, 'http://10.1.1.20/cgi-bin/mediaFileFind.cgi?action=findNextFile&object='+codigo+'&count=100')
cualquier.setopt(cualquier.HTTPAUTH, cualquiercosa.HTTPAUTH_DIGEST)
cualquier.setopt(cualquier.USERPWD, usuario + ':' + contra)
cualquier.setopt(cualquier.WRITEDATA, b_obj)
cualquier.perform()
cualquier.close()
pasocinco= b_obj.getvalue()
confirmacion=pasocinco.decode('utf8')
print(confirmacion)

nuevoarchi=open("datosdelrostro.txt","w")
nuevoarchi.write(confirmacion)
nuevoarchi.close()

#PASO 6 DEL API RECONOCIMIENTO DE ROSTRO 
cualquiercosa = pycurl.Curl()
cualquiercosa.setopt(cualquiercosa.URL, 'http://10.1.1.20/cgi-bin/mediaFileFind.cgi?action=findFile&object='+codigo+'&condition.Channel=2&condition.StartTime=2020-7-7%2020:00:00&condition.EndTime=2020-8-14%2020:00:00&condition.Types[0]=jpg&condition.Flags[0]=Event&condition.Events[0]=FaceRecognition&condition.DB.FaceRecognitionRecordFilter.RegType=RecSuccess&condition.DB.FaceRecognitionRecordFilter.StartTime=2020-7-7%2020:00:00&condition.DB.FaceRecognitionRecordFilter.EndTime=2020-8-14&condition.DB.FaceRecognitionRecordFilter.Person.Sex=Male&condition.DB.FaceRecognitionRecordFilter.Person.Country=CN&condiion.DB.FaceRecognitionRecordFilter.Person.Age[0]=25&condition.DB.FaceRecognitionRecordFilter.Person.Age[1]=40&condition.DB.FaceRecognitionRecordFilter.Person.Glasses=1&condition.DB.FaceRecognitionRecordFilter.GroupID[0]=10001&condition.DB.FaceRecognitionRecordFilter.GroupID[1]=10003&condition.DB.FaceRecognitionRecordFilter.GroupID[2]=10005&condition.DB.FaceRecognitionRecordFilter.SimilaryRange[0]=40&condition.DB.FaceRecognitionRecordFilter.SimilaryRange[1]=100')
cualquiercosa.setopt(cualquiercosa.HTTPAUTH, cualquiercosa.HTTPAUTH_DIGEST)
cualquiercosa.setopt(cualquiercosa.USERPWD, usuario + ':' + contra)
cualquiercosa.setopt(cualquiercosa.WRITEDATA, b_obj)
cualquiercosa.perform()
cualquiercosa.close()
get_body = b_obj.getvalue()
confirmacion=get_body.decode('utf8')
print(confirmacion)
#PASO 7 DEL API RECONOCIMIENTO DE ROSTRO 
cualquiercosa = pycurl.Curl()
cualquiercosa.setopt(cualquiercosa.URL, 'http://10.1.1.20/cgi-bin/mediaFileFind.cgi?action=findNextFile&object='+codigo+'&count=100')
cualquiercosa.setopt(cualquiercosa.HTTPAUTH, cualquiercosa.HTTPAUTH_DIGEST)
cualquiercosa.setopt(cualquiercosa.USERPWD, usuario + ':' + contra)
cualquiercosa.setopt(cualquiercosa.WRITEDATA, b_obj)
cualquiercosa.perform()
cualquiercosa.close()
get_body = b_obj.getvalue()
confirmacion=get_body.decode('utf8')
print(confirmacion)
